# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# Runs monthly to check for updates to npm dependencies.
version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/Frontend' # Location of package manifests
    schedule:
      interval: 'monthly'
    labels:
      - 'dependencies'
      - 'automerge'